version: '3.8'

services:
  fastapi:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=80
      - UVICORN_WORKERS=1
      - UVICORN_RELOAD=true
